"""Wire protocol for JSONL communication with remote exec helpers."""
from codeagent.wire.protocol import (
    MAX_LINE_LENGTH,
    WIRE_VERSION,
    WireMessage,
    decode_line,
    decode_request,
    encode_line,
    encode_request,
    make_accepted,
    make_capabilities,
    make_error,
    make_ping,
    make_pong,
    make_ready,
    make_request,
    make_result,
    make_session,
)

__all__ = [
    "MAX_LINE_LENGTH",
    "WIRE_VERSION",
    "WireMessage",
    "decode_line",
    "decode_request",
    "encode_line",
    "encode_request",
    "make_accepted",
    "make_capabilities",
    "make_error",
    "make_ping",
    "make_pong",
    "make_ready",
    "make_request",
    "make_result",
    "make_session",
]
